//! Autogenerated weights for `pallet_prime`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-07-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `VM-0-8-ubuntu`, CPU: `Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /root/numen
// benchmark
// pallet
// --runtime
// /root/numen_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_prime
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/prime/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_prime`.
pub trait WeightInfo {
	fn upgrade() -> Weight;
	fn set_key() -> Weight;
	fn remove_registrar() -> Weight;
}

/// Weights for `pallet_prime` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Prime::Key` (r:1 w:0)
	/// Proof: `Prime::Key` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn upgrade() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `60`
		//  Estimated: `1517`
		// Minimum execution time: 4_721_000 picoseconds.
		Weight::from_parts(5_129_000, 1517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Prime::Key` (r:1 w:1)
	/// Proof: `Prime::Key` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `60`
		//  Estimated: `1517`
		// Minimum execution time: 13_036_000 picoseconds.
		Weight::from_parts(14_073_000, 1517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Prime::Key` (r:1 w:0)
	/// Proof: `Prime::Key` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::Registrars` (r:1 w:1)
	/// Proof: `Identity::Registrars` (`max_values`: Some(1), `max_size`: Some(57002), added: 57497, mode: `MaxEncodedLen`)
	fn remove_registrar() -> Weight {
		Weight::from_parts(50_000_000, 58_487)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Prime::Key` (r:1 w:0)
	/// Proof: `Prime::Key` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn upgrade() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `60`
		//  Estimated: `1517`
		// Minimum execution time: 4_721_000 picoseconds.
		Weight::from_parts(5_129_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `Prime::Key` (r:1 w:1)
	/// Proof: `Prime::Key` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn set_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `60`
		//  Estimated: `1517`
		// Minimum execution time: 13_036_000 picoseconds.
		Weight::from_parts(14_073_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Prime::Key` (r:1 w:0)
	/// Proof: `Prime::Key` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Identity::Registrars` (r:1 w:1)
	/// Proof: `Identity::Registrars` (`max_values`: Some(1), `max_size`: Some(57002), added: 57497, mode: `MaxEncodedLen`)
	fn remove_registrar() -> Weight {
		Weight::from_parts(50_000_000, 58_487)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
