//! Autogenerated weights for `pallet_validator`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-09-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `numen-bench`, CPU: `Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/ubuntu/numen
// benchmark
// pallet
// --runtime
// /home/ubuntu/numen_runtime.compact.compressed.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --pallet
// pallet_validator
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/validator/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_validator`.
pub trait WeightInfo {
	fn lock() -> Weight;
	fn request_exit() -> Weight;
	fn set_stake_exempt() -> Weight;
	fn on_initialize(n: u32, ) -> Weight;
}

/// Weights for `pallet_validator` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Validator::DesiredValidators` (r:1 w:0)
	/// Proof: `Validator::DesiredValidators` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `Validator::PendingValidators` (r:1 w:1)
	/// Proof: `Validator::PendingValidators` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `Session::NextKeys` (r:1 w:0)
	/// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Identity::IdentityOf` (r:1 w:0)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(23535), added: 26010, mode: `MaxEncodedLen`)
	/// Storage: `Validator::RejoinCooldown` (r:1 w:1)
	/// Proof: `Validator::RejoinCooldown` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Validator::StakeExemptAccounts` (r:1 w:0)
	/// Proof: `Validator::StakeExemptAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Validator::ValidatorLocks` (r:1 w:1)
	/// Proof: `Validator::ValidatorLocks` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn lock() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `32630`
		//  Estimated: `36095`
		// Minimum execution time: 134_896_000 picoseconds.
		Weight::from_parts(142_741_000, 36095)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Validator::ValidatorLocks` (r:1 w:1)
	/// Proof: `Validator::ValidatorLocks` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Validator::PendingValidators` (r:1 w:1)
	/// Proof: `Validator::PendingValidators` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	fn request_exit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `32277`
		//  Estimated: `33487`
		// Minimum execution time: 55_631_000 picoseconds.
		Weight::from_parts(59_870_000, 33487)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Prime::Key` (r:1 w:0)
	/// Proof: `Prime::Key` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Validator::StakeExemptAccounts` (r:0 w:1)
	/// Proof: `Validator::StakeExemptAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn set_stake_exempt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `60`
		//  Estimated: `1517`
		// Minimum execution time: 15_007_000 picoseconds.
		Weight::from_parts(16_140_000, 1517)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Validator::ValidatorLocks` (r:1001 w:1000)
	/// Proof: `Validator::ValidatorLocks` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1000 w:1000)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1000 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1000 w:1000)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 1000]`.
	fn on_initialize(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `163 + n * (296 ±0)`
		//  Estimated: `3538 + n * (3774 ±0)`
		// Minimum execution time: 5_876_000 picoseconds.
		Weight::from_parts(6_186_000, 3538)
			// Standard Error: 52_947
			.saturating_add(Weight::from_parts(41_604_492, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().reads((4_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3774).saturating_mul(n.into()))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Validator::DesiredValidators` (r:1 w:0)
	/// Proof: `Validator::DesiredValidators` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `Validator::PendingValidators` (r:1 w:1)
	/// Proof: `Validator::PendingValidators` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	/// Storage: `Session::NextKeys` (r:1 w:0)
	/// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Identity::IdentityOf` (r:1 w:0)
	/// Proof: `Identity::IdentityOf` (`max_values`: None, `max_size`: Some(23535), added: 26010, mode: `MaxEncodedLen`)
	/// Storage: `Validator::RejoinCooldown` (r:1 w:1)
	/// Proof: `Validator::RejoinCooldown` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Validator::StakeExemptAccounts` (r:1 w:0)
	/// Proof: `Validator::StakeExemptAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Validator::ValidatorLocks` (r:1 w:1)
	/// Proof: `Validator::ValidatorLocks` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn lock() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `32630`
		//  Estimated: `36095`
		// Minimum execution time: 134_896_000 picoseconds.
		Weight::from_parts(142_741_000, 36095)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Validator::ValidatorLocks` (r:1 w:1)
	/// Proof: `Validator::ValidatorLocks` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Validator::PendingValidators` (r:1 w:1)
	/// Proof: `Validator::PendingValidators` (`max_values`: Some(1), `max_size`: Some(32002), added: 32497, mode: `MaxEncodedLen`)
	fn request_exit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `32277`
		//  Estimated: `33487`
		// Minimum execution time: 55_631_000 picoseconds.
		Weight::from_parts(59_870_000, 33487)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Prime::Key` (r:1 w:0)
	/// Proof: `Prime::Key` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Validator::StakeExemptAccounts` (r:0 w:1)
	/// Proof: `Validator::StakeExemptAccounts` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn set_stake_exempt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `60`
		//  Estimated: `1517`
		// Minimum execution time: 15_007_000 picoseconds.
		Weight::from_parts(16_140_000, 1517)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Validator::ValidatorLocks` (r:1001 w:1000)
	/// Proof: `Validator::ValidatorLocks` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1000 w:1000)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1000 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1000 w:1000)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 1000]`.
	fn on_initialize(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `163 + n * (296 ±0)`
		//  Estimated: `3538 + n * (3774 ±0)`
		// Minimum execution time: 5_876_000 picoseconds.
		Weight::from_parts(6_186_000, 3538)
			// Standard Error: 52_947
			.saturating_add(Weight::from_parts(41_604_492, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().reads((4_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes((3_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3774).saturating_mul(n.into()))
	}
}
